events {}

http {
  server {
    listen 8080;
    server_name _;

    location = /terraform/mcp {
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_request_buffering off;
      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
      proxy_pass http://terraform-mcp-v2-canary_app:8080/terraform/mcp;
    }

    location / {
      return 404;
    }
  }
}
